### ISSUE TITLE
TribunNews API with type not exists

### ISSUE THREAD

**Issue by axmad386** [satyawikananda/berita-indo-api#10]
# Tribun News missing type RSS
Hi, this is greate repo. But I encounter some problem. I think RSS Tribun News cannot use type, 
I was checked the RSS api
`https://api.tribunnews.com/rss/:type` for example `https://api.tribunnews.com/rss/bisnis` it return blank page
Or I miss something?
I can make PR to remove the type based route for tribunnews if you have no time

Oh, one more.. Can I contribute for making pagination?

**Comment by satyawikananda** [comment]
Hi, previously that endpoint is work, but I don't know is not work again, maybe they have change their endpoint I guess 🤔. Now I'm search that new endpoint again, if you find that endpoint, you can create a PR and fix this issue.

Yes, you can contribute for make a pagination to this API, PR are welcome :)

**Comment by axmad386** [comment]
I found that main rss api currenty cannot filter by type, but on subdomain still work. 
example
`api.tribunnews.com/rss/:type` is not working
`jateng.tribunnews.com/rss/:type` is ok
What do you think? I have 2 options
1. Separate the main and sub domain rss api
2. Add params like `zone` in addition of `type`
   example `:zone.tribunnews.com/rss/:type`

**Comment by satyawikananda** [comment]
I think option two is better for me. If you want to contribute, open PR for this issue, and since now Hacktoberfest, I'll add label Hacktoberfest on issue and on pull request.

**Comment by axmad386** [comment]
sorry, afk for weekend :smile: 
Thanks for the label, working on this :rocket:
