### ISSUE TITLE
402 Payment Required

### ISSUE THREAD

**Issue by dapoi** [satyawikananda/berita-indo-api#27]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/68842666/180912753-59920841-25b8-4dd0-a37e-5bd8d0794138.png">

**Comment by satyawikananda** [comment]
Thanks for the report. It seems like my Vercel account is blocked due by usage limit because one of my project. If you have any suggest for this, please inform me too. Thanks
![image](https://user-images.githubusercontent.com/33148052/180994160-14842800-5564-417b-823e-236ab3bc3622.png)
